'use strict';

/* ---------- Grupe musculare (folosite identic în hartă, date, i18n și worker) ---------- */
const MUSCLE_GROUPS = [
  'chest', 'shoulders', 'biceps', 'forearms', 'abs', 'quads', 'calves',
  'back', 'traps', 'triceps', 'glutes', 'hamstrings',
];

/* ---------- Bază de date exerciții ---------- */
/* videoId este intenționat null peste tot — se completează ulterior, per exercițiu,
   printr-o căutare reală (nu se inventează linkuri YouTube). */
const EXERCISES = [
  // ---- CHEST ----
  { id: 'chest-barbell-bench-press', muscleGroup: 'chest',
    name: { ro: 'Împins din culcat cu bara', en: 'Barbell Bench Press' },
    description: { ro: 'Culcat pe bancă, coboară bara controlat până la piept, apoi împinge-o până la extensia brațelor.', en: 'Lying on a bench, lower the bar under control to your chest, then press it back up to full arm extension.' },
    sets: '3-4', reps: '6-10', equipment: 'barbell', difficulty: 'intermediate', videoId: '4Y2ZdHCOXok' },
  { id: 'chest-incline-dumbbell-press', muscleGroup: 'chest',
    name: { ro: 'Împins înclinat cu gantere', en: 'Incline Dumbbell Press' },
    description: { ro: 'Pe bancă înclinată la 30-45°, împinge ganterele în sus până aproape de extensie completă, fără a bloca cotul brusc.', en: 'On a bench set to 30-45°, press the dumbbells up to near-full extension without locking the elbows abruptly.' },
    sets: '3', reps: '8-12', equipment: 'dumbbell', difficulty: 'intermediate', videoId: 'awEEyL5zGvU' },
  { id: 'chest-push-up', muscleGroup: 'chest',
    name: { ro: 'Flotări', en: 'Push-Up' },
    description: { ro: 'Corp drept ca o scândură, coboară pieptul spre podea, apoi împinge înapoi în poziția inițială.', en: 'Keep your body in a straight line, lower your chest toward the floor, then push back up.' },
    sets: '3', reps: '10-20', equipment: 'bodyweight', difficulty: 'beginner', videoId: 'WDIpL0pjun0' },
  { id: 'chest-cable-fly', muscleGroup: 'chest',
    name: { ro: 'Fluturări la cablu', en: 'Cable Fly' },
    description: { ro: 'Cu cablurile setate la înălțimea pieptului, adu mânerele într-un arc larg spre centru, ținând coatele ușor îndoite.', en: 'With cables set at chest height, bring the handles together in a wide arc, keeping a slight bend in the elbows.' },
    sets: '3', reps: '12-15', equipment: 'cable', difficulty: 'intermediate', videoId: 'eQ_NBB6OBH4' },

  // ---- SHOULDERS ----
  { id: 'shoulders-overhead-press', muscleGroup: 'shoulders',
    name: { ro: 'Împins din picioare deasupra capului', en: 'Overhead Press' },
    description: { ro: 'Din picioare, cu bara la nivelul umerilor, împinge-o vertical deasupra capului fără să arcuiești excesiv spatele.', en: 'Standing with the bar at shoulder height, press it straight overhead without excessively arching your back.' },
    sets: '3-4', reps: '6-10', equipment: 'barbell', difficulty: 'intermediate', videoId: 'KEAS2bypjFg' },
  { id: 'shoulders-lateral-raise', muscleGroup: 'shoulders',
    name: { ro: 'Ridicări laterale cu gantere', en: 'Lateral Raise' },
    description: { ro: 'Ridică ganterele lateral până la nivelul umerilor, cu coatele ușor îndoite și mișcare controlată.', en: 'Raise the dumbbells out to the sides up to shoulder height, elbows slightly bent, controlled movement.' },
    sets: '3', reps: '12-15', equipment: 'dumbbell', difficulty: 'beginner', videoId: 'pgrWjBfaFe8' },
  { id: 'shoulders-front-raise', muscleGroup: 'shoulders',
    name: { ro: 'Ridicări frontale cu gantere', en: 'Front Raise' },
    description: { ro: 'Ridică o ganteră (sau ambele) în față până la nivelul umerilor, fără să legeni corpul pentru elan.', en: 'Raise a dumbbell (or both) in front of you to shoulder height, without swinging your body for momentum.' },
    sets: '3', reps: '10-12', equipment: 'dumbbell', difficulty: 'beginner', videoId: 'qmFQTDYwpsg' },
  { id: 'shoulders-face-pull', muscleGroup: 'shoulders',
    name: { ro: 'Tracțiune la față (cablu)', en: 'Face Pull' },
    description: { ro: 'Trage frânghia de la cablu spre față, la nivelul ochilor, depărtând coatele și rotind ușor umerii spre spate.', en: 'Pull the rope attachment toward your face at eye level, spreading your elbows and rotating your shoulders slightly back.' },
    sets: '3', reps: '12-15', equipment: 'cable', difficulty: 'beginner', videoId: 'wnPX6Fwe-Fg' },

  // ---- BICEPS ----
  { id: 'biceps-barbell-curl', muscleGroup: 'biceps',
    name: { ro: 'Flexii cu bara', en: 'Barbell Curl' },
    description: { ro: 'Din picioare, cu bara prinsă cu priză supinată, flexează coatele ridicând bara spre piept, fără să legeni spatele.', en: 'Standing with an underhand grip on the bar, curl it up toward your chest without swinging your back.' },
    sets: '3', reps: '8-12', equipment: 'barbell', difficulty: 'beginner', videoId: 'JJB8XgKltA8' },
  { id: 'biceps-dumbbell-curl', muscleGroup: 'biceps',
    name: { ro: 'Flexii cu gantere', en: 'Dumbbell Curl' },
    description: { ro: 'Flexează câte un braț sau ambele simultan, rotind ușor încheietura spre exterior în vârful mișcării.', en: 'Curl one arm at a time or both together, rotating the wrist slightly outward at the top of the movement.' },
    sets: '3', reps: '10-12', equipment: 'dumbbell', difficulty: 'beginner', videoId: 'av7-8igSXTs' },
  { id: 'biceps-hammer-curl', muscleGroup: 'biceps',
    name: { ro: 'Flexii tip „ciocan"', en: 'Hammer Curl' },
    description: { ro: 'Ține ganterele cu priză neutră (palmele față în față) și flexează coatele fără a roti încheietura.', en: 'Hold the dumbbells with a neutral grip (palms facing each other) and curl without rotating the wrist.' },
    sets: '3', reps: '10-12', equipment: 'dumbbell', difficulty: 'beginner', videoId: 'G7hy-AxQwcQ' },
  { id: 'biceps-cable-curl', muscleGroup: 'biceps',
    name: { ro: 'Flexii la cablu', en: 'Cable Curl' },
    description: { ro: 'Cu bara sau mânerul atașat la cablul de jos, flexează coatele menținând tensiune constantă pe biceps.', en: 'With a bar or handle attached to the low cable, curl while keeping constant tension on the biceps.' },
    sets: '3', reps: '12-15', equipment: 'cable', difficulty: 'beginner', videoId: '2MUEL4nL6hA' },

  // ---- FOREARMS ----
  { id: 'forearms-wrist-curl', muscleGroup: 'forearms',
    name: { ro: 'Flexii de încheietură', en: 'Wrist Curl' },
    description: { ro: 'Așezat, cu antebrațele sprijinite pe coapse sau o bancă, flexează doar încheieturile ridicând ganterele.', en: 'Seated, forearms resting on your thighs or a bench, curl only your wrists to raise the dumbbells.' },
    sets: '3', reps: '15-20', equipment: 'dumbbell', difficulty: 'beginner', videoId: '7ac_qmBjkFI' },
  { id: 'forearms-reverse-curl', muscleGroup: 'forearms',
    name: { ro: 'Flexii inversate', en: 'Reverse Curl' },
    description: { ro: 'Ca la flexiile clasice, dar cu priză pronată (palmele în jos), pentru accent pe antebrațe.', en: 'Like a standard curl, but with an overhand grip (palms down) to emphasize the forearms.' },
    sets: '3', reps: '10-15', equipment: 'barbell', difficulty: 'beginner', videoId: 'jCjrLiXyiv8' },
  { id: 'forearms-farmers-carry', muscleGroup: 'forearms',
    name: { ro: 'Mers cu greutăți (farmer\'s carry)', en: "Farmer's Carry" },
    description: { ro: 'Ține câte o ganteră grea în fiecare mână și mergi drept, cu umerii traşi înapoi, pe o distanță sau un timp stabilit.', en: 'Hold a heavy dumbbell in each hand and walk tall, shoulders back, for a set distance or time.' },
    sets: '3', reps: '30-40m', equipment: 'dumbbell', difficulty: 'intermediate', videoId: 'Fkzk_RqlYig' },
  { id: 'forearms-dead-hang', muscleGroup: 'forearms',
    name: { ro: 'Atârnare la bară', en: 'Dead Hang' },
    description: { ro: 'Atârnă la bara de tracțiuni cu brațele întinse, umerii relaxați, cât mai mult timp posibil, controlat.', en: 'Hang from a pull-up bar with straight arms and relaxed shoulders for as long as you can, under control.' },
    sets: '3', reps: '20-40s', equipment: 'bodyweight', difficulty: 'beginner', videoId: 'kOw9c6AjJYA' },

  // ---- ABS ----
  { id: 'abs-plank', muscleGroup: 'abs',
    name: { ro: 'Plancă', en: 'Plank' },
    description: { ro: 'Sprijină-te pe antebrațe și vârfurile picioarelor, corp drept ca o scândură, fără să lași șoldurile în jos.', en: 'Support yourself on your forearms and toes, body in a straight line, without letting your hips sag.' },
    sets: '3', reps: '30-60s', equipment: 'bodyweight', difficulty: 'beginner', videoId: 'mwlp75MS6Rg' },
  { id: 'abs-crunch', muscleGroup: 'abs',
    name: { ro: 'Abdomene clasice', en: 'Crunch' },
    description: { ro: 'Culcat cu genunchii îndoiți, ridică omoplații de la sol contractând abdomenul, fără să tragi de gât.', en: 'Lying with knees bent, lift your shoulder blades off the floor by contracting your abs, without pulling on your neck.' },
    sets: '3', reps: '15-20', equipment: 'bodyweight', difficulty: 'beginner', videoId: '0OxOI3sAIrM' },
  { id: 'abs-leg-raise', muscleGroup: 'abs',
    name: { ro: 'Ridicări de picioare', en: 'Leg Raise' },
    description: { ro: 'Culcat sau atârnat la bară, ridică picioarele întinse (sau ușor îndoite) până la orizontală, controlat.', en: 'Lying down or hanging from a bar, raise your straight (or slightly bent) legs up to horizontal, under control.' },
    sets: '3', reps: '10-15', equipment: 'bodyweight', difficulty: 'intermediate', videoId: 'Pr1ieGZ5atk' },
  { id: 'abs-russian-twist', muscleGroup: 'abs',
    name: { ro: 'Rotații tip rusesc', en: 'Russian Twist' },
    description: { ro: 'Așezat, trunchi ușor înclinat spate, rotește trunchiul dintr-o parte în alta, cu sau fără greutate în mâini.', en: 'Seated with your torso leaning slightly back, rotate side to side, with or without weight in your hands.' },
    sets: '3', reps: '20-30', equipment: 'bodyweight', difficulty: 'beginner', videoId: 'Nl-txzo-7WQ' },

  // ---- QUADS ----
  { id: 'quads-back-squat', muscleGroup: 'quads',
    name: { ro: 'Genuflexiuni cu bara', en: 'Back Squat' },
    description: { ro: 'Cu bara pe umeri, coboară șoldurile până coapsele sunt cel puțin paralele cu solul, apoi revino în picioare.', en: 'With the bar on your upper back, lower your hips until thighs are at least parallel to the floor, then stand back up.' },
    sets: '3-4', reps: '6-10', equipment: 'barbell', difficulty: 'intermediate', videoId: 'nEQQle9-0NA' },
  { id: 'quads-leg-press', muscleGroup: 'quads',
    name: { ro: 'Presă de picioare', en: 'Leg Press' },
    description: { ro: 'Așezat la aparat, împinge platforma cu picioarele fără a bloca genunchii complet la extensie.', en: 'Seated in the machine, push the platform away with your legs without locking your knees at full extension.' },
    sets: '3', reps: '10-15', equipment: 'machine', difficulty: 'beginner', videoId: 'G4elY53UFOQ' },
  { id: 'quads-walking-lunge', muscleGroup: 'quads',
    name: { ro: 'Fandări mergând', en: 'Walking Lunge' },
    description: { ro: 'Fă un pas mare înainte, coboară genunchiul din spate spre sol, apoi ridică-te și continuă cu piciorul celălalt.', en: 'Step forward, lower your back knee toward the floor, then stand up and continue with the other leg.' },
    sets: '3', reps: '10-12/picior', equipment: 'dumbbell', difficulty: 'intermediate', videoId: 'IUMtekTfVVQ' },
  { id: 'quads-leg-extension', muscleGroup: 'quads',
    name: { ro: 'Extensii de picioare', en: 'Leg Extension' },
    description: { ro: 'Așezat la aparat, extinde genunchii ridicând greutatea, apoi coboară controlat fără să lași placa să cadă.', en: 'Seated in the machine, extend your knees to lift the weight, then lower it back under control.' },
    sets: '3', reps: '12-15', equipment: 'machine', difficulty: 'beginner', videoId: 'YyvSfVjQeL0' },

  // ---- CALVES ----
  { id: 'calves-standing-calf-raise', muscleGroup: 'calves',
    name: { ro: 'Ridicări pe vârfuri (din picioare)', en: 'Standing Calf Raise' },
    description: { ro: 'Din picioare, la aparat sau cu greutate pe umeri, ridică-te pe vârfuri cât mai sus, apoi coboară controlat.', en: 'Standing at a machine or with weight on your shoulders, rise onto your toes as high as possible, then lower under control.' },
    sets: '3-4', reps: '12-20', equipment: 'machine', difficulty: 'beginner', videoId: 'ndQc4mz4mBU' },
  { id: 'calves-seated-calf-raise', muscleGroup: 'calves',
    name: { ro: 'Ridicări pe vârfuri (din șezut)', en: 'Seated Calf Raise' },
    description: { ro: 'Așezat la aparat, cu genunchii îndoiți, ridică-te pe vârfuri pentru a implica în special gambele profunde.', en: 'Seated at the machine with knees bent, rise onto your toes to emphasize the deeper calf muscles.' },
    sets: '3', reps: '15-20', equipment: 'machine', difficulty: 'beginner', videoId: 'smyXy_dhXo8' },
  { id: 'calves-single-leg-calf-raise', muscleGroup: 'calves',
    name: { ro: 'Ridicări pe vârfuri pe un picior', en: 'Single-Leg Calf Raise' },
    description: { ro: 'Pe un picior, cu mâna sprijinită de un perete pentru echilibru, ridică-te pe vârf cât mai sus posibil.', en: 'On one leg, hand resting on a wall for balance, rise onto your toes as high as possible.' },
    sets: '3', reps: '12-15/picior', equipment: 'bodyweight', difficulty: 'intermediate', videoId: 'ORT4oJ_R8Qs' },
  { id: 'calves-dumbbell-calf-raise', muscleGroup: 'calves',
    name: { ro: 'Ridicări pe vârfuri cu gantere', en: 'Dumbbell Calf Raise' },
    description: { ro: 'Din picioare, cu câte o ganteră în fiecare mână, ridică-te pe vârfuri, cu o pauză scurtă în vârful mișcării.', en: 'Standing with a dumbbell in each hand, rise onto your toes, pausing briefly at the top.' },
    sets: '3', reps: '15-20', equipment: 'dumbbell', difficulty: 'beginner', videoId: 'wxwY7GXxL4k' },

  // ---- BACK ----
  { id: 'back-pull-up', muscleGroup: 'back',
    name: { ro: 'Tracțiuni la bară', en: 'Pull-Up' },
    description: { ro: 'Atârnat la bară cu priză pronată, trage-te în sus până bărbia depășește bara, apoi coboară controlat.', en: 'Hanging from the bar with an overhand grip, pull yourself up until your chin clears the bar, then lower under control.' },
    sets: '3-4', reps: '5-10', equipment: 'bodyweight', difficulty: 'advanced', videoId: 'vw5Xmu5CIew' },
  { id: 'back-barbell-row', muscleGroup: 'back',
    name: { ro: 'Ramat cu bara', en: 'Barbell Row' },
    description: { ro: 'Trunchi aplecat înainte, spate drept, trage bara spre abdomen, ducând coatele înapoi și strângând omoplații.', en: 'Bend forward with a flat back and pull the bar toward your abdomen, driving your elbows back and squeezing your shoulder blades.' },
    sets: '3-4', reps: '8-10', equipment: 'barbell', difficulty: 'intermediate', videoId: '9Xf3DqxxTBA' },
  { id: 'back-lat-pulldown', muscleGroup: 'back',
    name: { ro: 'Tracțiuni la helcometru (lat pulldown)', en: 'Lat Pulldown' },
    description: { ro: 'Așezat la aparat, trage bara spre partea superioară a pieptului, ducând coatele în jos și înapoi.', en: 'Seated at the machine, pull the bar down toward your upper chest, driving your elbows down and back.' },
    sets: '3', reps: '10-12', equipment: 'machine', difficulty: 'beginner', videoId: '6MLs17iyK9I' },
  { id: 'back-seated-cable-row', muscleGroup: 'back',
    name: { ro: 'Ramat la cablu din șezut', en: 'Seated Cable Row' },
    description: { ro: 'Așezat cu genunchii ușor îndoiți, trage mânerul spre abdomen, ținând spatele drept și strângând omoplații.', en: 'Seated with knees slightly bent, pull the handle toward your abdomen, keeping your back straight and squeezing your shoulder blades.' },
    sets: '3', reps: '10-12', equipment: 'cable', difficulty: 'beginner', videoId: 'IzoCF_b3cIY' },

  // ---- TRAPS ----
  { id: 'traps-barbell-shrug', muscleGroup: 'traps',
    name: { ro: 'Ridicări din umeri cu bara', en: 'Barbell Shrug' },
    description: { ro: 'Din picioare, cu bara ținută în față, ridică umerii direct în sus spre urechi, apoi coboară controlat.', en: 'Standing with the bar held in front, shrug your shoulders straight up toward your ears, then lower under control.' },
    sets: '3', reps: '10-15', equipment: 'barbell', difficulty: 'beginner', videoId: '9xGqgGFAtiM' },
  { id: 'traps-dumbbell-shrug', muscleGroup: 'traps',
    name: { ro: 'Ridicări din umeri cu gantere', en: 'Dumbbell Shrug' },
    description: { ro: 'La fel ca la bară, dar cu câte o ganteră în fiecare mână, permițând o traiectorie mai naturală.', en: 'Same movement as the barbell version, but with a dumbbell in each hand, allowing a more natural path.' },
    sets: '3', reps: '12-15', equipment: 'dumbbell', difficulty: 'beginner', videoId: '8lP_eJvClSA' },
  { id: 'traps-upright-row', muscleGroup: 'traps',
    name: { ro: 'Ramat vertical', en: 'Upright Row' },
    description: { ro: 'Trage bara vertical de-a lungul corpului, până aproape de bărbie, ducând coatele sus și în afară.', en: 'Pull the bar straight up along your body toward chin height, leading with your elbows out and up.' },
    sets: '3', reps: '10-12', equipment: 'barbell', difficulty: 'intermediate', videoId: 'KzYlXWXVw3o' },
  { id: 'traps-farmers-carry-traps', muscleGroup: 'traps',
    name: { ro: 'Mers cu greutăți (accent trapez)', en: "Farmer's Carry (Trap Focus)" },
    description: { ro: 'Ca la farmer\'s carry clasic, dar cu greutăți foarte grele și umeri activ trași în jos și înapoi.', en: 'Like a standard farmer\'s carry, but with heavier loads and shoulders actively pulled down and back.' },
    sets: '3', reps: '20-30m', equipment: 'dumbbell', difficulty: 'intermediate', videoId: 'Fkzk_RqlYig' },

  // ---- TRICEPS ----
  { id: 'triceps-close-grip-bench-press', muscleGroup: 'triceps',
    name: { ro: 'Împins cu priză îngustă', en: 'Close-Grip Bench Press' },
    description: { ro: 'Ca la împinsul clasic din culcat, dar cu mâinile la lățimea umerilor, pentru accent pe triceps.', en: 'Like a standard bench press, but with hands at shoulder width to emphasize the triceps.' },
    sets: '3', reps: '8-10', equipment: 'barbell', difficulty: 'intermediate', videoId: 'UYJsFzqdgK4' },
  { id: 'triceps-pushdown', muscleGroup: 'triceps',
    name: { ro: 'Extensii la cablu (triceps pushdown)', en: 'Triceps Pushdown' },
    description: { ro: 'La cablul de sus, extinde coatele împingând bara sau frânghia în jos, ținând coatele lipite de corp.', en: 'At the high cable, extend your elbows to push the bar or rope down, keeping your elbows tucked to your sides.' },
    sets: '3', reps: '12-15', equipment: 'cable', difficulty: 'beginner', videoId: '_w-HpW70nSQ' },
  { id: 'triceps-overhead-extension', muscleGroup: 'triceps',
    name: { ro: 'Extensii de triceps deasupra capului', en: 'Overhead Triceps Extension' },
    description: { ro: 'Ține o ganteră cu ambele mâini deasupra capului, coboară-o în spatele capului, apoi extinde coatele.', en: 'Hold a dumbbell overhead with both hands, lower it behind your head, then extend your elbows back up.' },
    sets: '3', reps: '10-12', equipment: 'dumbbell', difficulty: 'beginner', videoId: 'v1qDINLCb8Q' },
  { id: 'triceps-dip', muscleGroup: 'triceps',
    name: { ro: 'Flotări la paralele (dips)', en: 'Dip' },
    description: { ro: 'Sprijinit pe paralele, coboară corpul îndoind coatele, apoi împinge înapoi în poziția inițială.', en: 'Supported on parallel bars, lower your body by bending your elbows, then press back up to the start.' },
    sets: '3', reps: '8-15', equipment: 'bodyweight', difficulty: 'intermediate', videoId: 'J3WYrjNDLI4' },

  // ---- GLUTES ----
  { id: 'glutes-hip-thrust', muscleGroup: 'glutes',
    name: { ro: 'Împins din șolduri (hip thrust)', en: 'Hip Thrust' },
    description: { ro: 'Cu spatele superior sprijinit pe o bancă și bara pe șolduri, împinge șoldurile în sus până la extensie completă.', en: 'With your upper back on a bench and the bar across your hips, drive your hips up to full extension.' },
    sets: '3-4', reps: '8-12', equipment: 'barbell', difficulty: 'intermediate', videoId: 'S_uZP4UH6J0' },
  { id: 'glutes-glute-bridge', muscleGroup: 'glutes',
    name: { ro: 'Podul fesier', en: 'Glute Bridge' },
    description: { ro: 'Culcat cu genunchii îndoiți, ridică șoldurile de la sol contractând fesierii, apoi coboară controlat.', en: 'Lying with knees bent, lift your hips off the floor by squeezing your glutes, then lower under control.' },
    sets: '3', reps: '15-20', equipment: 'bodyweight', difficulty: 'beginner', videoId: 'cvKZXsz-QIA' },
  { id: 'glutes-bulgarian-split-squat', muscleGroup: 'glutes',
    name: { ro: 'Genuflexiune bulgărească', en: 'Bulgarian Split Squat' },
    description: { ro: 'Cu piciorul din spate sprijinit pe o bancă, coboară pe piciorul din față până genunchiul din spate aproape atinge solul.', en: 'With your back foot elevated on a bench, lower on your front leg until your back knee nearly touches the floor.' },
    sets: '3', reps: '8-12/picior', equipment: 'dumbbell', difficulty: 'intermediate', videoId: 'HBYGeyb4sSM' },
  { id: 'glutes-cable-kickback', muscleGroup: 'glutes',
    name: { ro: 'Extensie de șold la cablu (kickback)', en: 'Cable Kickback' },
    description: { ro: 'Cu glezna prinsă în cablul de jos, extinde șoldul ducând piciorul în spate, contractând fesierul la final.', en: 'With the ankle attached to the low cable, extend your hip by driving your leg back, squeezing the glute at the end.' },
    sets: '3', reps: '12-15/picior', equipment: 'cable', difficulty: 'beginner', videoId: 'bVrmtCI00Ys' },

  // ---- HAMSTRINGS ----
  { id: 'hamstrings-romanian-deadlift', muscleGroup: 'hamstrings',
    name: { ro: 'Îndreptări românești', en: 'Romanian Deadlift' },
    description: { ro: 'Cu genunchii ușor îndoiți, coboară bara aproape de picioare împingând șoldurile în spate, apoi revino în picioare.', en: 'With knees slightly bent, lower the bar close to your legs by pushing your hips back, then stand back up.' },
    sets: '3-4', reps: '8-10', equipment: 'barbell', difficulty: 'intermediate', videoId: 'dFR11xt1GbQ' },
  { id: 'hamstrings-leg-curl', muscleGroup: 'hamstrings',
    name: { ro: 'Flexii de picioare (leg curl)', en: 'Leg Curl' },
    description: { ro: 'La aparat, culcat sau așezat, flexează genunchii aducând călcâiele spre fesieri, apoi revino controlat.', en: 'On the machine, lying or seated, curl your heels toward your glutes, then return under control.' },
    sets: '3', reps: '10-15', equipment: 'machine', difficulty: 'beginner', videoId: 'P7-RxTVe6O0' },
  { id: 'hamstrings-good-morning', muscleGroup: 'hamstrings',
    name: { ro: '„Good morning" (aplecări cu bara)', en: 'Good Morning' },
    description: { ro: 'Cu bara pe umeri și genunchii ușor îndoiți, apleacă trunchiul înainte din șolduri, cu spatele drept, apoi revino.', en: 'With the bar on your upper back and knees slightly bent, hinge forward from the hips with a flat back, then return.' },
    sets: '3', reps: '8-10', equipment: 'barbell', difficulty: 'advanced', videoId: 'VkNcc0BQrpA' },
  { id: 'hamstrings-nordic-curl', muscleGroup: 'hamstrings',
    name: { ro: 'Flexii nordice de ischio-gambieri', en: 'Nordic Hamstring Curl' },
    description: { ro: 'Îngenuncheat, cu gleznele fixate, coboară trunchiul înainte cât mai controlat posibil, folosind ischio-gambierii pentru frânare.', en: 'Kneeling with your ankles anchored, lower your torso forward as slowly as possible, using your hamstrings to control the descent.' },
    sets: '3', reps: '5-8', equipment: 'bodyweight', difficulty: 'advanced', videoId: 'CMoOdh_wr8Y' },
];
