// Catalogul librăriei — sursa unică de adevăr pentru chat-ul AI.
// Titlurile trebuie să corespundă cu id-urile din ../script.js (CATALOG),
// fiindcă frontend-ul evidențiază cărțile recomandate după `id`.
export const CATALOG = [
  {
    id: 'omul-care-plantat-copaci',
    title: 'Omul care plantat copaci',
    author: 'Jean Giono',
    genre: 'Ficțiune scurtă',
    price: '24 lei',
    mood: 'liniște, reconectare cu natura, nevoie să încetinești',
    description: 'O poveste scurtă despre răbdare și fapte simple, făcute constant, care schimbă o lume întreagă. Pentru cineva copleșit de viteza vieții.',
  },
  {
    id: 'micul-print',
    title: 'Micul Prinț',
    author: 'Antoine de Saint-Exupéry',
    genre: 'Ficțiune / clasic',
    price: '29 lei',
    mood: 'nostalgie, nevoie de simplitate, dor de copilărie, sens pierdut',
    description: 'O fabulă despre ce contează cu adevărat, spusă simplu. Bună când lucrurile "de adult" au devenit prea complicate.',
  },
  {
    id: 'norwegian-wood',
    title: 'Pădurea norvegiană',
    author: 'Haruki Murakami',
    genre: 'Ficțiune literară',
    price: '52 lei',
    mood: 'singurătate, dor, iubire pierdută, melancolie',
    description: 'Un roman melancolic despre iubire, pierdere și maturizare. Pentru cineva care duce dorul cuiva sau al unei perioade din viață.',
  },
  {
    id: 'mandrie-si-prejudecata',
    title: 'Mândrie și prejudecată',
    author: 'Jane Austen',
    genre: 'Romantism / clasic',
    price: '39 lei',
    mood: 'nevoie de speranță, iubire, ceva cald și optimist',
    description: 'Un clasic al romantismului, plin de umor și speranță. Bun când ai nevoie de o poveste caldă, cu final bun.',
  },
  {
    id: 'stapanul-inelelor',
    title: 'Stăpânul Inelelor',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    price: '89 lei',
    mood: 'nevoie de evadare, aventură, curaj, prietenie',
    description: 'O epopee despre curaj și prietenie într-o lume întreagă de descoperit. Perfectă pentru cineva care vrea să evadeze complet din realitate.',
  },
  {
    id: 'dune',
    title: 'Dune',
    author: 'Frank Herbert',
    genre: 'Science fiction',
    price: '65 lei',
    mood: 'evadare, ambiție, nevoie de o lume nouă, curiozitate intelectuală',
    description: 'Politică, putere și supraviețuire pe o planetă deșertică. Pentru cineva care vrea ficțiune densă, cu multe straturi.',
  },
  {
    id: 'fata-disparuta',
    title: 'Fata dispărută',
    author: 'Gillian Flynn',
    genre: 'Thriller',
    price: '45 lei',
    mood: 'nevoie de adrenalină, distragere, minte plictisită',
    description: 'Un thriller psihologic cu răsturnări de situație, ideal când vrei ceva care să-ți acapareze complet atenția și să te distragă de la griji.',
  },
  {
    id: 'sapiens',
    title: 'Sapiens: Scurtă istorie a omenirii',
    author: 'Yuval Noah Harari',
    genre: 'Non-ficțiune / istorie',
    price: '58 lei',
    mood: 'curiozitate, nevoie de perspectivă, gânduri mărețe care pun lucrurile mărunte în context',
    description: 'O privire de ansamblu asupra istoriei omenirii. Bună când problemele zilnice par uriașe și ai nevoie de perspectivă.',
  },
  {
    id: 'puterea-obisnuintei',
    title: 'Puterea obișnuinței',
    author: 'Charles Duhigg',
    genre: 'Dezvoltare personală',
    price: '44 lei',
    mood: 'nevoie de schimbare, obiceiuri proaste, lipsă de disciplină, vrei un nou început',
    description: 'Cum se formează obiceiurile și cum le poți schimba pe cele care nu te mai ajută. Pentru cineva care vrea un nou început concret.',
  },
  {
    id: 'essentialism',
    title: 'Essentialism',
    author: 'Greg McKeown',
    genre: 'Dezvoltare personală',
    price: '48 lei',
    mood: 'epuizare, burnout, prea multe pe cap, nevoie să reduci, supraîncărcare la muncă',
    description: 'Despre arta de a face mai puține lucruri, dar mai bine. Pentru cineva epuizat, care simte că face prea multe și nimic bine.',
  },
  {
    id: 'curajul-de-a-nu-fi-pe-plac',
    title: 'Curajul de a nu fi pe plac',
    author: 'Ichiro Kishimi, Fumitake Koga',
    genre: 'Psihologie / filozofie',
    price: '46 lei',
    mood: 'anxietate socială, teamă de judecata altora, nevoie de granițe, presiunea așteptărilor',
    description: 'Un dialog despre eliberarea de nevoia de aprobare a celorlalți. Pentru cineva sufocat de așteptările altora.',
  },
  {
    id: 'meditatii',
    title: 'Meditații',
    author: 'Marcus Aurelius',
    genre: 'Filozofie / stoicism',
    price: '35 lei',
    mood: 'anxietate, nevoie de calm, control asupra propriilor gânduri, stres',
    description: 'Gândurile private ale unui împărat roman despre calm, control și acceptare. Pentru cineva anxios, care caută liniște mentală.',
  },
  {
    id: 'anul-gandirii-magice',
    title: 'Anul gândirii magice',
    author: 'Joan Didion',
    genre: 'Memorii',
    price: '42 lei',
    mood: 'doliu, pierdere, durere, nevoie de a se simți înțeles în suferință',
    description: 'O mărturie sinceră despre doliu și pierdere. Nu vindecă, dar te face să te simți mai puțin singur în durere.',
  },
  {
    id: 'jurnalul-lui-bridget-jones',
    title: 'Jurnalul lui Bridget Jones',
    author: 'Helen Fielding',
    genre: 'Comedie romantică',
    price: '38 lei',
    mood: 'nevoie de ceva ușor, amuzant, autoironic, seară proastă, vrei să râzi',
    description: 'Comedie ușoară și autoironică. Perfectă când vrei ceva care nu te solicită, dar te face să râzi.',
  },
];
